### ISSUE TITLE
Magical book to-do list

### ISSUE THREAD

**Issue by sqyyy-jar** [sqyyy-jar/vanilla-extras#1]
- [ ] Implement renaming
  - [x] Basis
  - [ ] Add increasing cost
- [ ] Implement merging
  - [x] Basis
  - [ ] Add cost calculation
  - [x] Add validity checks
  - [x] (Add enchantment compatibility checks)
  - [ ] Item + Item merging
  - [ ] Replace merging with modifying
- [ ] Implement enchanting
  - [x] Basis
  - [ ] Add cost calculation
  - [x] (Add item compatibility checks)
- [ ] Implement enchantments
  - [x] Add enchantment registry
- [ ] Implement villager trades
